


export const RECEIVE_ATTRIBUTES = 'RECEIVE_ATTRIBUTES';
export const RECEIVE_METADATA = 'RECEIVE_METADATA';
export const RECEIVE_EFFECTS = 'RECEIVE_EFFECTS';
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS';
export const RECEIVE_GROUP = 'RECEIVE_GROUP';
export const RECEIVE_EQUIPMENT = 'RECEIVE_EQUIPMENT';
export const RECEIVE_QUESTS = 'RECEIVE_QUESTS';
export const RECEIVE_CHANNELS = 'RECEIVE_CHANNELS';
export const RECEIVE_CHANNEL_UPDATE = 'RECEIVE_CHANNEL_UPDATE';
export const RECEIVE_ACTIONBAR = 'RECEIVE_ACTIONBAR';

export const UPDATE_FONTSIZE = 'UPDATE_FONTSIZE';
export const SET_CHARACTER_PANEL = 'SET_CHARACTER_PANEL';



