export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const SOCKET = 'SOCKET';
export const SEND_MESSAGE = 'SEND_MESSAGE';


export const RECEIVE_ATTRIBUTES = 'RECEIVE_ATTRIBUTES';
export const RECEIVE_METADATA = 'RECEIVE_METADATA';
export const RECEIVE_MAP = 'RECEIVE_MAP';
export const RECEIVE_EFFECTS = 'RECEIVE_EFFECTS';
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS';

export const UPDATE_FONTSIZE = 'UPDATE_FONTSIZE';