export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const SOCKET = 'SOCKET';
export const SOCKET_STATUS = 'SOCKET_STATUS';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const AUTO_CONNECT = 'AUTO_CONNECT';


export const RECEIVE_ATTRIBUTES = 'RECEIVE_ATTRIBUTES';
export const RECEIVE_METADATA = 'RECEIVE_METADATA';
export const RECEIVE_MAP = 'RECEIVE_MAP';
export const RECEIVE_EFFECTS = 'RECEIVE_EFFECTS';
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS';
export const RECEIVE_COMBAT = 'RECEIVE_COMBAT';
export const RECEIVE_GROUP = 'RECEIVE_GROUP';
export const RECEIVE_EQUIPMENT = 'RECEIVE_EQUIPMENT';
export const RECEIVE_QUESTS = 'RECEIVE_QUESTS';

export const UPDATE_FONTSIZE = 'UPDATE_FONTSIZE';
export const SET_CHARACTER_PANEL = 'SET_CHARACTER_PANEL';

export const SEND_LAST_ITEM_IDENTIFY = 'SEND_LAST_ITEM_IDENTIFY';
