export const RECEIVE_EFFECTS = 'RECEIVE_EFFECTS';
export const UPDATE_EFFECT = 'UPDATE_EFFECT';
export const REMOVE_EFFECT = 'REMOVE_EFFECT';
export const ADD_EFFECT = 'ADD_EFFECT';
export const CALCULATE_EFFECT_TIMERS = 'CALCULATE_EFFECT_TIMERS';
