export const RECEIVE_SETTINGS = 'SETTINGS/RECEIVE_SETTINGS';
export const SET_CHARACTER_PANEL = 'SETTINGS/SET_CHARACTER_PANEL';
export const UPDATE_FONTSIZE = 'UPDATE_FONTSIZE';
export const TOGGLE_PLAYER_SETTING = 'TOGGLE_PLAYER_SETTING';



