export const RECEIVE_ATTRIBUTES = 'RECEIVE_ATTRIBUTES';
export const RECEIVE_GROUP = 'RECEIVE_GROUP';
export const RECEIVE_EQUIPMENT = 'RECEIVE_EQUIPMENT';

export const SEND_LAST_ITEM_IDENTIFY = 'SEND_LAST_ITEM_IDENTIFY';
